In [1]:
# Importing the Libraries

from tensorflow.keras.models import load_model
import numpy as np
import pickle

# Load the model and tokenizer

model = load_model('nextword1.h5')
tokenizer = pickle.load(open('tokenizer1.pkl', 'rb'))

words = np.array(list(tokenizer.word_index.keys()))
words_indexes = np.array(list(tokenizer.word_index.values()))

In [41]:
def Predict_Next_Words(model, tokenizer, text):
    """
        In this function we are using the tokenizer and models trained
        and we are creating the sequence of the text entered and then
        using our model to predict and return the the predicted word.
    
    """
    for i in range(3):
        sequence = tokenizer.texts_to_sequences([text])[0]
#         print(f"1111 sequence: {sequence} {len(sequence)}")
        sequence = np.array(sequence)
#         print(f"2222 sequence: {sequence} {len(sequence)}")

#         preds = model.predict_classes(sequence)
        predict_x=model.predict(sequence)
#         print(f"predict_x: {predict_x} {len(predict_x[0][:-1])}")
#         classes_x=np.argmax(predict_x,axis=1)
        predict_x_0 = predict_x[0][1:]
#         for x in predict_x_0:
#             print(str(x), end=" ")
        classes_x = predict_x_0[predict_x_0 > .01]
    
#         print(f"classes_x: {classes_x}")
        
        preds = classes_x
#         print(f"preds: {preds}")
        predicted_word = words[predict_x_0 > .001]
        
#         for key, value in tokenizer.word_index.items():
#             if value == preds:
#                 predicted_word = key
#                 break
        
#         print(f"predicted_word: {predicted_word}")
        return predicted_word

In [42]:
"""
    We are testing our model and we will run the model
    until the user decides to stop the script.
    While the script is running we try and check if 
    the prediction can be made on the text. If no
    prediction can be made we just continue.

"""

# text1 = "at the dull"
# text2 = "collection of textile"
# text3 = "what a strenuous"
# text4 = "."

while(True):

    text = input("Enter your line: ")
    
    if text == ".":
        print("Ending The Program.....")
        break
    
    else:
        try:
            text = text.split(" ")
            text = text[-1]

            text = ''.join(text)
            
            print(f"text: {text}")
            predicted = Predict_Next_Words(model, tokenizer, text)
            
            print(f"predicted: {predicted}")
            
        except Exception as e:
            print(f"Error: {str(e)}")
            continue

Enter your line:  to


text: to
predicted: ['the' 'and' 'his' 'it' 'in' 'a' 'gregor' 'him' 'her' 'but' 'they' 'all'
 'be' 'have' "gregor's" 'so' 'this' 'himself' 'even' 'one' 'their' 'what'
 'them' 'you' 'just' 'any' 'do' 'get' 'go' 'some' 'see' 'much' 'where'
 'open' 'which' 'come' 'an' 'bed' 'everything' 'let' 'being' 'work'
 'three' 'make' 'mr' 'look' 'slowly' 'side' 'grete' 'think' 'lay' 'feel'
 'its' 'always' 'say' 'herself' 'me' 'know' 'each' 'your' 'move' 'help'
 'immediately' 'behind' 'sleep' 'put' 'called' 'anything' 'face' 'close'
 'hear' 'leave' 'take' 'set' 'want' 'give' 'keep' 'stay' 'us' 'eat'
 'whether' 'themselves' 'turn' 'seven' 'use' 'notice' 'fall' 'bring'
 'speak' 'stand' 'both' 'carry' 'calm' 'actually' 'crawl' 'forget'
 'sleeping' 'god' 'try' 'tell' 'find' 'listen' 'hold' 'earn' 'cut'
 'overcome' 'pay' 'quietly' 'rush' 'throw' 'show' 'wait' 'start' 'spare'
 'stop' 'send' 'sit' 'live' 'catch' 'remove' 'push' 'control' 'call'
 'worry' 'our' 'save' 'talk' 'drive' 'bear' 'breathe' 'fetch' '

Enter your line:  .


Ending The Program.....


In [77]:
words_indexes

array([   1,    2,    3, ..., 2614, 2615, 2616])

In [79]:
len(words_indexes)

2616

In [78]:
words

array(['the', 'to', 'and', ..., 'agreed', 'confirmation', 'destination'],
      dtype='<U17')

In [80]:
len(words_indexes)

2616

In [43]:
a = np.array([.1, .5, 1, .05, .8, 2])
a

array([0.1 , 0.5 , 1.  , 0.05, 0.8 , 2.  ])

In [44]:
a * 10

array([ 1. ,  5. , 10. ,  0.5,  8. , 20. ])

In [50]:
a[-3:][a[-3:] > 1]

array([2.])

In [8]:
np.ar

5

In [9]:
a[np.argmax(a)]

2.0

In [25]:
b = a > .5
b

array([False, False,  True, False,  True,  True])

In [13]:
a[a >= .8]

array([1. , 0.8, 2. ])

In [28]:
np.where(a >= .8, a)

ValueError: either both or neither of x and y should be given

In [22]:
len(tokenizer.word_index.items())

2616

In [53]:
c = np.array(list(tokenizer.word_index.values()))
c

array([   1,    2,    3, ..., 2614, 2615, 2616])

In [69]:
d = c > 100
d

array([False, False, False, ...,  True,  True,  True])

In [64]:
e = np.array(list(tokenizer.word_index.keys()))

In [71]:
e[d]

array(['went', 'come', 'away', ..., 'agreed', 'confirmation',
       'destination'], dtype='<U17')

In [66]:
len(c)

2616

In [67]:
len(e)

2616

In [70]:
len(d)

2616